site_name: BelajarPowerShell.com
site_url: https://example.com/
#docs_dir: '../docs'
extra_css:
  - stylesheets/extra.css
theme:
  language: en 
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary:  deepblue #deep purple #deep orange #indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
 
 ##https://github.com/tylerdotrar/mkdocs-coverpage
  # palette:
  #   # Light Mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: deep purple # deep orange
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to Dark Mode

  #   # Dark Mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: teal
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to Light Mode
  # https://github.com/tylerdotrar/mkdocs-coverpage
  # custom_dir: assets 
  #custom_dir: overrides
  features:
    - tabs
    - instant
    - content.code.annotate
    - navigation.indexes          # Implied section 'index.md' files
    - navigation.tabs             # Static upper section tabs (exist)
    #- navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.instant          # Keep navigation from reloading
    - navigation.instant.progress # Display page loading progress-bar ( > 400ms)
    - search.highlight            # Highlight all occurrences of queried string
    - search.share                # Search Query can be copied to Clipboard
    - search.suggest              # Display likeliest completion for the last queried word
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-L3H13G3ETP
    # feedback:
    #   title: Was this page helpful?
    #   ratings:
    #     - icon: material/emoticon-happy-outline
    #       name: This page was helpful
    #       data: 1
    #       note: >-
    #         Thanks for your feedback!
    #     - icon: material/emoticon-sad-outline
    #       name: This page could be improved
    #       data: 0
    #       note: >- 
    #         Thanks for your feedback! Help us improve this page by
    #         using our <a href="..." target="_blank" rel="noopener">feedback form</a>.    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: belajarpowershell
      repo: belajarpowershell
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  #- optimize
  - search
  - table-reader
  - roamlinks # Obsidian Style Image Support ![[<attachment_name>]]
#   - codeinclude

#https://github.com/tylerdotrar/mkdocs-coverpage
# # Custom Homepage Elements
# #home_cover_image: images/HyperV-network-switch.png # This path starts at your root mkdocs directory.
# home_tagline: Shadow Wizards Only
# home_description: |
#   This site is an example showcase for my "mkdocs-coverpage" repository.

# # Gradient Color
# home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# # Custom Homepage Button(s)
# home_button1_name: Kubernetes Lab Setup                   # Comment this parameter out to remove the button.
# home_button1_url: /kubernetes-lab-setup/000-Prerequisites/                       # This path starts at your root mkdocs directory.
# home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
# home_button1_icon: people                        # Options: "people", "gear", "image"
# home_button1_blurb: |                            # Short description of this button / section.
#   This joker navigates to the shadow wizard armory located in "/kubernetes-lab-setup/000-Prerequisites/001-Hyper-V-Host-Specification.md"

# home_button2_name: Belajar PowerShell   # Comment this parameter out to remove the button.
# home_button2_url: kubernetes-lab-setup/ #100-alpine1/    # This path starts at your root mkdocs directory.
# home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
# home_button2_icon: gear       # Options: "people", "gear", "image"
# home_button2_blurb: |         # Short description of this button / section.
#   This goober navigates to some important thingies located in "/Folder2/index.md"
nav:
  # - Section:
  #   - kubernetes-lab-setup/100-alpine1/manual-steps/101-DHCP-server.md
  #   - Page 1: index.md
  - Kubernetes Lab Setup:
      - index.md
      #- ReadMe.md
      - High level Design: 
          - kubernetes-lab-setup/000-Prerequisites/001-Hyper-V-Host-Specification.md
          - kubernetes-lab-setup/000-Prerequisites/002-High-Level-node-setup.md
          - kubernetes-lab-setup/000-Prerequisites/002-vi-basics.md
          - kubernetes-lab-setup/000-Prerequisites/003-clone-repository.md
          - kubernetes-lab-setup/000-Prerequisites/004-Hyper-V-VM-creation.md
      - Management Server install alpine1:
          - kubernetes-lab-setup/100-alpine1/100-alpine1-setup.md
          #- kubernetes-lab-setup/100-alpine1/1000-Clone-repository (copy).md
          - kubernetes-lab-setup/100-alpine1/101-ssh-to-alpine1.md
          - kubernetes-lab-setup/100-alpine1/102-Clone-repository.md
          #- kubernetes-lab-setup/100-alpine1/103-setup-using-ansible-manual.md
          - kubernetes-lab-setup/100-alpine1/103-setup-using-ansible.md
          - Manual steps to install alpine1:
                        - Readme First:  kubernetes-lab-setup/100-alpine1/manual-steps/readme.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/101-DHCP-server.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/102-setup-router.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/103-setup-dns.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/104-setup-nginx.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/105-nfs.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/106-tftp.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/107-cloud-init.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/108-DHCP-for-PXE.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/109-setup-boot-files-part1-PXE.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/110-setup-boot-files-part2-OS.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/111-setup-boot-files-part3-pxelinux.cfg.md
                        #- kubernetes-lab-setup/100-alpine1/manual-steps/112-New-single-VM-setup-Ubuntu-autoinstall.md
                        - kubernetes-lab-setup/100-alpine1/manual-steps/113-generate-user-data-multipleVM.md
                        - kubernetes-lab-setup/100-alpine1/104-Validation.md
      - Install Ubuntu on VM's created:
          - Ubuntu installation :
                    - kubernetes-lab-setup/100-alpine1/113-Install-Ubuntu.md
      - k3s installation:
          - k3s Lightweight Kubernetes Installation:
                - kubernetes-lab-setup/200-kubernetes/200-ReadMe.md
                - kubernetes-lab-setup/200-kubernetes/201-SSH-keys-setup.md
                - kubernetes-lab-setup/200-kubernetes/202-Setup-k3s-with-Ansible.md
                - kubernetes-lab-setup/200-kubernetes/204-k3s-setup-complete.md
          # - Manual Steps:
          #   - kubernetes-lab-setup/200-kubernetes/manual-steps/202-Ansible-inventory.md
          #   - kubernetes-lab-setup/200-kubernetes/manual-steps/203-Setup-k3s-with-Ansible.md
          #   # - 900-Explainers/PXELINUX.md
          #   # - 900-Explainers/generate-user-data-multipleVM.md
          #   # - 900-Explainers/generate-user-data-reference.md
# new section
  - Deploying Kubernetes applications: deploy-k3s-applications/readme.md 
# - applications\BelajarPowerShell.md
  - HashiCorp Vault - Selfnotes: 
        - vault/readme.md
        - vault/A001-Vault-notes -initial-setup.md
        - vault/A001-Vault-start.md
        - vault/A002-Azure-vault-prereq.md
        - vault/A003-Vault-notes-Vault-azure-Initial-setup.md
        - vault/A004-Vault-notes-Vault-azure-generate-SP.md
        - vault/A005-Vault-Policies.md
        - vault/B001-PKI-CA.md
        - vault/D001-Vault-common-commands.md
        - vault/zzz-additional-info-001.md
        - vault/zzz-additional-info-002 -all-vault-config.md



copyright: |
  &copy; 2024 <a href="https://github.com/belajarpowershell"  target="_blank" rel="noopener">Suresh Solomon</a>