##https://docs.giantswarm.io/advanced/access-management/authentication-azure-ad/
# clusterrole-admin.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-group-admin
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "configmaps"] # Add more resources as needed
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# clusterrolebinding-azure-group-admin.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-group-admin-binding
subjects:
- kind: Group
  name: a26b3125-56c8-4489-ae28-4a1490ee1986
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: azure-group-admin
  apiGroup: rbac.authorization.k8s.io


# to remove tokens
  kubelogin remove-tokens
